python3 train_seg.py train \
  --dataroot ../dataset/HumanBody/train/mit \
  --test_dataroot ../dataset/HumanBody/test/shrec \
	--weight_decay 0.05 --optim adamw \
	--lr 1e-4 --n_epoch 200 --gamma 0.1 \
	--batch_size 16 --channel 10 \
	--heads 6 --patch_size 64 \
	--dim 384 --encoder_depth 12 \
	--decoder_depth 6 --decoder_dim 512 --decoder_num_heads 16 \
  --augment_scale --augment_orient \
	--name "human" --face_pos --lw1 1 --lw2 1 \
	--dataset_name human --seg_parts 50 \
    --fpn